site_name: Giant Swarm Docs

dev_addr: '0.0.0.0:8000'

docs_dir: sources

theme_dir: ./theme/giantswarm/

pages:
# Introduction
- ['index.md', 'Welcome']

# Installation
- ['installation/cheatsheet.md', 'Installation', 'Cheat Sheet']
- ['installation/gettingstarted.md', 'Installation', 'Getting Started']
- ['installation/gettingstarted2.md', 'Installation', 'Getting Started - Part 2']

# Guides
- ['guides/ruby_on_rails.md', 'Guides', 'Rails']
- ['guides/symfony.md', 'Guides', 'PHP and Symfony']
- ['guides/python.md', 'Guides', 'Python']
- ['guides/java.md', 'Guides', 'Java']

# Reference
- ['reference/index.md', 'Reference', 'Overview']
- ['reference/env.md', 'Reference', 'Working with environments']
