baseurl = "https://docs.giantswarm.io"
languageCode = "en"
title = "Giant Swarm Documentation"
pluralizeListTitles = false

[Blackfriday]
    plainIdAnchors = true

[[menu.main]]
    name = "Fundamentals"
    url = "/fundamentals/"
    weight = 20
[[menu.main]]
    name = "Guides"
    url = "/guides/"
    weight = 30
[[menu.main]]
    name = "Reference"
    url = "/reference/"
    weight = 40
[[menu.main]]
    name = "Video"
    url = "/video/"
    weight = 50
[[menu.main]]
    name = "FAQ"
    url = "/faq/"
    weight = 60
