baseurl = "http://docs.giantswarm.io"
languageCode = "en"
title = "Giant Swarm Documentation"
pluralizeListTitles = false
[[menu.main]]
    name = "What is Giant Swarm?"
    url = "/what-is-giant-swarm/"
    weight = 20
[[menu.main]]
    name = "Guides and Tutorials"
    url = "/guides/"
    weight = 30
[[menu.main]]
    name = "Reference"
    url = "/reference/"
    weight = 40
