apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: docs
  name: content
  labels:
    app: docs
    component: content
spec:
  replicas: 2
  template:
    metadata:
      name: content
      labels:
        app: docs
        component: content
    spec:
      containers:
        - image: quay.io/giantswarm/docs:{{ .BuildInfo.SHA }}
          name: content
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              cpu: 0.2
              memory: 10M
            limits:
              cpu: 0.5
              memory: 20M
      imagePullSecrets:
        - name: registry-pull-secret
